# Generated by Django 2.2.3 on 2024-07-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo_codes', '0002_auto_20240720_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCodeManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
